version: '3.5'
services:
  app:
    image: jjrom/stac-proxy:latest
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 4112:80
    environment:
      - INPUT_STAC_URL=${INPUT_STAC_URL:-}
      - PUBLIC_ENDPOINT=${PUBLIC_ENDPOINT:-http://localhost:4112}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 1m
      timeout: 5s